url: "https://lasersafetysquad.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "LSS Site" # the name of your site, e.g. ACME Corp.
ignore_theme_config: TRUE
livereload: TRUE
permalink: /:categories/:title:output_ext
sass:
  sass_dir: _sass
  style: expanded